Singular value decomposition is a generalization of the eigen- decomposition of a square Matrix to a non-square matrix.
$$
M =U \Sigma V^T
$$
Where, $M$ is $m \times  n$ matrix, $U$ is $m \times  m$ matrixreal or complex unitary matrix, $V^T$ is $n \times  n$ real or complex unitary matrix  and  $\Sigma$ is $m \times  n$ rectangular diagonal matrix with non-negative real numbers

In [ ]:
#@title Import numpy
import numpy as np
SIGMA ='\N{greek capital letter sigma}'

In [ ]:
#@title Create a random complex matrix of m x n size { run: "auto" }
m = 4 #@param {type:"slider", min:2, max:10, step:1}
n=2 #@param {type:"slider", min:2, max:10, step:1}
M= np.random.randn(m, n) + 1j*np.random.randn(m, n) # Create a random matrix M
np.set_printoptions(linewidth=np.inf)# forces the print function to print each row of matrix a one line only
print("M = ",M)

print("\n\nCalculate SVD for M and test it.\n")
U, S, Vt = np.linalg.svd(M, full_matrices=True)
SS = np.zeros((m, n), float)
np.fill_diagonal(SS, S)
print ("U =\n", U)
print ("\n"+SIGMA+" =\n", SS)
print ("\nVt =\n", Vt)

print("\n Complex M matrix gives complex U and V matric")
M_out=np.dot(np.dot(U,SS),Vt)
print("\n\nU "+SIGMA+" Vt =\n",M_out)
print("\nand,\n\n M =\n",M)

In [ ]:
#@title Create a random real matrix of m x n size { run: "auto" }
m = 5 #@param {type:"slider", min:2, max:10, step:1}
n=3 #@param {type:"slider", min:2, max:10, step:1}
M= np.random.randn(m, n)  # Create a random matrix M
np.set_printoptions(linewidth=np.inf)# forces the print function to print each row of matrix a one line only
print("M = ",M)

print("\n\nCalculate SVD for M and test it.\n")
U, S, Vt = np.linalg.svd(M, full_matrices=True)
SS = np.zeros((m, n), float)
np.fill_diagonal(SS, S)
print ("U =\n", U)
print ("\n"+SIGMA+" =\n", SS)
print ("\nVt =\n", Vt)
print("\n Real M matrix gives real U and V matric")
M_out=np.dot(np.dot(U,SS),Vt)
print("\n\nU "+SIGMA+" Vt =\n",M_out)
print("\nand,\n\n M =\n",M)

M =  [[ 0.44447834  0.21296221 -0.76113164]
 [ 0.71806192  0.35111807  0.89716619]
 [ 1.77983796  0.07343762  2.46836464]
 [ 1.73441259  0.00573417 -0.22308894]
 [-0.14491088  2.31392887 -0.38487947]]


Calculate SVD for M and test it.

U =
 [[ 0.08001562  0.14637584  0.47172826 -0.86542441  0.02616612]
 [-0.32979351  0.16417508 -0.08645337 -0.07773607 -0.92236961]
 [-0.88194963  0.06741303 -0.22717683 -0.18296452  0.36405357]
 [-0.29293454  0.13134053  0.83337465  0.44975473  0.01209986]
 [ 0.1455608   0.96427476 -0.1545175   0.09613724  0.12596914]]

Σ =
 [[3.41947647 0.         0.        ]
 [0.         2.3667309  0.        ]
 [0.         0.         1.6790568 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Vt =
 [[-0.67265767  0.05018697 -0.73824991]
 [ 0.16520586  0.9826991  -0.08372273]
 [ 0.72127573 -0.17827995 -0.66931127]]

 Real M matrix gives real U and V matric


U Σ Vt =
 [[ 0.44447834  0.21296221 -0.76113164]
 [ 0.71806192  0.35111807  0.89716619